import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms governing your use of Frontend Coach.',
};

const LAST_UPDATED = 'June 20, 2026';

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <header className="mb-10">
        <p className="text-xs font-semibold uppercase tracking-widest text-primary">Legal</p>
        <h1 className="mt-2 text-3xl font-extrabold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
      </header>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-sm leading-relaxed text-foreground">

        <section>
          <h2 className="mb-3 text-lg font-semibold">1. Acceptance</h2>
          <p>
            By creating an account or using Frontend Coach (the &quot;Service&quot;), you agree to these
            Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">2. Description of service</h2>
          <p>
            Frontend Coach provides AI-powered interview preparation for frontend engineers,
            including mock interview sessions, answer feedback, a question bank, spaced repetition
            study plans, and CV-personalised question generation.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">3. Accounts</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>You must provide a valid email address and keep your credentials secure.</li>
            <li>You are responsible for all activity under your account.</li>
            <li>You must be at least 16 years old to use the Service.</li>
            <li>We may suspend accounts that violate these terms or attempt to abuse AI limits.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">4. Free and Pro tiers</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>
              <strong>Free tier:</strong> one practice session per calendar day, full question bank
              access, AI feedback, and basic score breakdowns.
            </li>
            <li>
              <strong>Pro tier:</strong> unlimited sessions, full history, spaced repetition, voice
              input, weak-area coaching, and priority AI responses.
            </li>
            <li>
              Pro subscriptions are billed monthly or as a one-time lifetime purchase via Polar.
              Prices are shown at checkout and may change with notice.
            </li>
            <li>
              Refunds are handled at our discretion. Contact{' '}
              <a href="mailto:letrung95@gmail.com" className="text-primary underline">letrung95@gmail.com</a>{' '}
              within 7 days of purchase for refund requests.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">5. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Attempt to bypass session limits, rate limits, or subscription gates.</li>
            <li>Scrape, copy, or redistribute question bank content at scale.</li>
            <li>Use the Service to generate harmful, abusive, or deceptive content.</li>
            <li>Reverse-engineer or attempt to extract AI prompts or internal logic.</li>
            <li>Share account credentials or resell access.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">6. AI-generated content</h2>
          <p>
            Feedback, questions, and study content are generated by AI and may contain errors.
            They are provided for educational and preparation purposes only — not as professional
            career advice. Always verify technical information from authoritative sources.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">7. Intellectual property</h2>
          <p>
            The Service, its design, question content, and handbooks are owned by Frontend Coach.
            You may use the content for personal interview preparation only. Commercial use,
            redistribution, or publication without written permission is prohibited.
          </p>
          <p className="mt-2">
            Your answers and CV content remain yours. By submitting them, you grant us a limited
            licence to process them solely to deliver the Service features.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">8. Availability and changes</h2>
          <p>
            We aim for high availability but do not guarantee uninterrupted access. We may modify,
            suspend, or discontinue features with reasonable notice. We may update these terms;
            continued use after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">9. Disclaimer and limitation of liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. To the fullest extent
            permitted by law, Frontend Coach is not liable for indirect, incidental, or consequential
            damages, including lost job opportunities or career outcomes. Our total liability for
            any claim is limited to the amount you paid in the 3 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">10. Governing law</h2>
          <p>
            These terms are governed by the laws of Vietnam. Disputes shall be resolved by
            the courts of Ho Chi Minh City, Vietnam.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold">11. Contact</h2>
          <p>
            Questions about these terms:{' '}
            <a href="mailto:letrung95@gmail.com" className="text-primary underline">letrung95@gmail.com</a>
          </p>
        </section>

      </div>

      <div className="mt-12 flex gap-4 text-sm text-muted-foreground">
        <Link href="/privacy" className="hover:text-foreground underline">Privacy Policy</Link>
        <Link href="/" className="hover:text-foreground">← Home</Link>
      </div>
    </div>
  );
}
