/**
 * One searchable record = one handbook section (or one glossary term).
 * The client search overlay loads an array of these (generated by
 * scripts/generate-resources-search-index.ts) and matches against `text`.
 */
export interface ResourceSearchRecord {
  /** Route slug, e.g. "react-deep-dive" or "glossary". */
  handbook: string;
  /** Display label for the source, e.g. "React Deep Dive". */
  handbookTitle: string;
  /** Deep link to the section, e.g. "/resources/react-deep-dive#hooks". */
  url: string;
  /** Section heading or glossary term — shown as the result title. */
  sectionTitle: string;
  /** Plain-text haystack (HTML/SVG stripped) used for matching + snippet. */
  text: string;
}
