/**
 * Phase-4 content sprint: JavaScript core gap-fill specs.
 * Subtopics absent from the existing 24 JS questions, mapped against the
 * JavaScript Core handbook ToC (types & coercion, scope, iterators, modules,
 * memory/GC, async patterns, functional patterns, platform internals).
 */
import type { QuestionSpec } from './question-spec-types';

const FILE = 'javascript.json';
const TOPIC = 'JavaScript';

export const JS_CORE_GAP_SPECS: QuestionSpec[] = [
  {
    key: 'js-type-coercion-internals',
    file: FILE, topic: TOPIC,
    subtopic: '🔀 Type Coercion — ToPrimitive Internals',
    difficulty: 'mid', type: 'conceptual',
    question: 'How does JavaScript type coercion actually work under the hood — what roles do ToPrimitive, valueOf, and toString play, and why does [] + {} differ from {} + []?',
    tags: ['coercion', 'toprimitive', 'types', 'fundamentals'],
  },
  {
    key: 'js-scope-hoisting-tdz',
    file: FILE, topic: TOPIC,
    subtopic: '📦 Scope, Hoisting & the TDZ',
    difficulty: 'mid', type: 'conceptual',
    question: 'How do var, let, and const differ in scoping and hoisting behavior, what is the temporal dead zone, and how does the engine set up scopes before execution?',
    tags: ['scope', 'hoisting', 'tdz', 'let-const'],
  },
  {
    key: 'js-iterators-generators',
    file: FILE, topic: TOPIC,
    subtopic: '🔁 Iterators & Generators',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do the iterator and iterable protocols work in JavaScript, and how do generators let you build lazy sequences, pausable computations, and custom iteration for data structures?',
    tags: ['iterators', 'generators', 'protocols', 'lazy-evaluation'],
  },
  {
    key: 'js-async-generators-iteration',
    file: FILE, topic: TOPIC,
    subtopic: '🔁 Async Generators & for-await',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do async generators and for await...of work, and when would you use them over Promise.all for paginated APIs, event streams, or rate-limited batch processing?',
    tags: ['async-generators', 'for-await', 'streams', 'pagination'],
  },
  {
    key: 'js-symbols-well-known',
    file: FILE, topic: TOPIC,
    subtopic: '🏷 Symbols & Well-Known Symbols',
    difficulty: 'senior', type: 'conceptual',
    question: 'What problems do Symbols solve in JavaScript, and how do well-known symbols like Symbol.iterator, Symbol.toPrimitive, and Symbol.hasInstance let you customize language behavior?',
    tags: ['symbols', 'well-known-symbols', 'metaprogramming'],
  },
  {
    key: 'js-esm-cjs-module-internals',
    file: FILE, topic: TOPIC,
    subtopic: '📦 ESM vs CJS — Module Internals',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do ES modules differ from CommonJS at the engine level — live bindings vs value copies, static analysis, circular dependency handling, and top-level await?',
    tags: ['esm', 'commonjs', 'modules', 'circular-dependencies'],
  },
  {
    key: 'js-tree-shaking-side-effects',
    file: FILE, topic: TOPIC,
    subtopic: '🌳 Tree Shaking & Side Effects',
    difficulty: 'senior', type: 'tradeoff',
    question: 'What makes code tree-shakeable, how do bundlers use ESM static structure and the sideEffects flag, and why do barrel files and class decorators defeat dead-code elimination?',
    tags: ['tree-shaking', 'bundling', 'side-effects', 'esm'],
  },
  {
    key: 'js-event-delegation-propagation',
    file: FILE, topic: TOPIC,
    subtopic: '🎯 Event Delegation & Propagation',
    difficulty: 'mid', type: 'conceptual',
    question: 'How do event capturing, bubbling, and delegation work in the DOM, and how would you build a delegated event system for a list with thousands of interactive rows?',
    tags: ['events', 'delegation', 'bubbling', 'dom'],
  },
  {
    key: 'js-debounce-throttle-from-scratch',
    file: FILE, topic: TOPIC,
    subtopic: '⏲ Debounce & Throttle — Implementation',
    difficulty: 'mid', type: 'conceptual',
    question: 'Implement debounce and throttle from scratch — including leading/trailing edge options, cancellation, and the closure mechanics that make them work.',
    tags: ['debounce', 'throttle', 'closures', 'implementation'],
  },
  {
    key: 'js-closure-memory-retention',
    file: FILE, topic: TOPIC,
    subtopic: '🧠 Closure Memory Retention',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do closures retain memory in JavaScript, why can a single shared scope object keep large data alive unexpectedly, and how do you diagnose closure-driven leaks in heap snapshots?',
    tags: ['closures', 'memory', 'heap-snapshot', 'leaks'],
  },
  {
    key: 'js-weakmap-weakset-usecases',
    file: FILE, topic: TOPIC,
    subtopic: '🫥 WeakMap & WeakSet Use Cases',
    difficulty: 'senior', type: 'conceptual',
    question: 'When do WeakMap and WeakSet beat Map and Set — covering private instance data, DOM node metadata, and memoization caches that must not block garbage collection?',
    tags: ['weakmap', 'weakset', 'gc', 'memoization'],
  },
  {
    key: 'js-garbage-collection-internals',
    file: FILE, topic: TOPIC,
    subtopic: '🗑 Garbage Collection Internals',
    difficulty: 'senior', type: 'conceptual',
    question: 'How does generational garbage collection work in V8 — the scavenger, mark-sweep-compact, and write barriers — and how does GC pressure show up as frame drops in real apps?',
    tags: ['gc', 'v8', 'generational', 'performance'],
  },
  {
    key: 'js-abortcontroller-cancellation',
    file: FILE, topic: TOPIC,
    subtopic: '🛑 AbortController & Cancellation',
    difficulty: 'senior', type: 'conceptual',
    question: 'How does AbortController provide composable cancellation for fetch, event listeners, and custom async work — and how do you propagate one signal through layered async operations?',
    tags: ['abortcontroller', 'cancellation', 'fetch', 'async'],
  },
  {
    key: 'js-promise-from-scratch',
    file: FILE, topic: TOPIC,
    subtopic: '🤝 Promises — Build One from Scratch',
    difficulty: 'senior', type: 'conceptual',
    question: 'Walk through implementing a Promises/A+ compliant promise from scratch — state machine, then-chaining, thenable assimilation, and why resolution must be asynchronous.',
    tags: ['promises', 'promises-aplus', 'implementation', 'async'],
  },
  {
    key: 'js-call-apply-bind-internals',
    file: FILE, topic: TOPIC,
    subtopic: '🪢 call/apply/bind — Implementation',
    difficulty: 'mid', type: 'conceptual',
    question: 'How do call, apply, and bind control the this binding, how would you implement bind from scratch, and what happens when bound functions are used with new?',
    tags: ['this', 'bind', 'call-apply', 'implementation'],
  },
  {
    key: 'js-property-descriptors-accessors',
    file: FILE, topic: TOPIC,
    subtopic: '🔧 Property Descriptors & Accessors',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do property descriptors, getters/setters, and Object.freeze/seal/preventExtensions work — and how do libraries use defineProperty for computed properties and API deprecation warnings?',
    tags: ['descriptors', 'defineproperty', 'getters-setters', 'immutability'],
  },
  {
    key: 'js-deep-clone-structuredclone',
    file: FILE, topic: TOPIC,
    subtopic: '🧬 Deep Cloning — structuredClone vs JSON',
    difficulty: 'mid', type: 'tradeoff',
    question: 'Compare structuredClone, JSON.parse(JSON.stringify()), and manual recursive cloning — covering circular references, special types like Date/Map/Set, functions, and performance.',
    tags: ['cloning', 'structuredclone', 'serialization'],
  },
  {
    key: 'js-floating-point-bigint',
    file: FILE, topic: TOPIC,
    subtopic: '🔢 Floating Point & BigInt',
    difficulty: 'mid', type: 'conceptual',
    question: 'Why does 0.1 + 0.2 !== 0.3 in JavaScript, what are safe integer limits, and how do you handle money calculations and 64-bit IDs correctly with or without BigInt?',
    tags: ['floating-point', 'bigint', 'precision', 'numbers'],
  },
  {
    key: 'js-tagged-template-literals',
    file: FILE, topic: TOPIC,
    subtopic: '🏷 Tagged Template Literals',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do tagged template literals work mechanically, and how do libraries like styled-components, graphql-tag, and SQL sanitizers exploit them to build safe embedded DSLs?',
    tags: ['template-literals', 'dsl', 'styled-components', 'sanitization'],
  },
  {
    key: 'js-error-handling-architecture',
    file: FILE, topic: TOPIC,
    subtopic: '🚨 Error Handling Architecture',
    difficulty: 'senior', type: 'system_design',
    question: 'How would you design error handling for a large frontend app — custom error classes, the cause chain, global handlers for unhandled rejections, and preserving async stack traces?',
    tags: ['errors', 'error-cause', 'unhandled-rejection', 'observability'],
  },
  {
    key: 'js-currying-composition',
    file: FILE, topic: TOPIC,
    subtopic: 'λ Currying & Function Composition',
    difficulty: 'mid', type: 'conceptual',
    question: 'What are currying, partial application, and function composition in JavaScript — how do you implement curry and pipe, and where do these patterns genuinely improve production code?',
    tags: ['currying', 'composition', 'functional-programming'],
  },
  {
    key: 'js-immutability-structural-sharing',
    file: FILE, topic: TOPIC,
    subtopic: '🧊 Immutability & Structural Sharing',
    difficulty: 'senior', type: 'conceptual',
    question: 'How do immutable update patterns and structural sharing work — what does Immer do with Proxies under the hood, and when does immutability help or hurt performance?',
    tags: ['immutability', 'immer', 'structural-sharing', 'proxy'],
  },
  {
    key: 'js-observer-pubsub-eventemitter',
    file: FILE, topic: TOPIC,
    subtopic: '📣 Observer vs Pub/Sub — EventEmitter',
    difficulty: 'mid', type: 'system_design',
    question: 'Implement a typed EventEmitter from scratch and explain how the observer and pub/sub patterns differ — including memory-leak risks from forgotten subscriptions.',
    tags: ['observer', 'pubsub', 'eventemitter', 'patterns'],
  },
  {
    key: 'js-event-loop-node-vs-browser',
    file: FILE, topic: TOPIC,
    subtopic: '🔄 Event Loop — Node vs Browser',
    difficulty: 'senior', type: 'conceptual',
    question: 'How does the Node.js event loop (timers, poll, check phases, setImmediate, process.nextTick) differ from the browser event loop with its rendering pipeline and requestAnimationFrame?',
    tags: ['event-loop', 'nodejs', 'raf', 'rendering'],
  },
  {
    key: 'js-transpilation-polyfills',
    file: FILE, topic: TOPIC,
    subtopic: '🔧 Transpilation & Polyfills',
    difficulty: 'mid', type: 'conceptual',
    question: 'What is the difference between transpiling syntax and polyfilling APIs — how do Babel, core-js, and browserslist work together, and what does differential serving change?',
    tags: ['babel', 'polyfills', 'browserslist', 'transpilation'],
  },
  {
    key: 'js-web-streams-backpressure',
    file: FILE, topic: TOPIC,
    subtopic: '🌊 Web Streams & Backpressure',
    difficulty: 'senior', type: 'system_design',
    question: 'How do ReadableStream, WritableStream, and TransformStream work — what is backpressure, and how would you stream-process a 500 MB file or a streaming fetch response without exhausting memory?',
    tags: ['streams', 'backpressure', 'fetch', 'memory'],
  },
  {
    key: 'js-regex-catastrophic-backtracking',
    file: FILE, topic: TOPIC,
    subtopic: '💥 Regex — Catastrophic Backtracking',
    difficulty: 'senior', type: 'conceptual',
    question: 'What causes catastrophic backtracking in regular expressions, how can a crafted input freeze your app or server (ReDoS), and how do you write linear-time-safe patterns?',
    tags: ['regex', 'redos', 'backtracking', 'security'],
  },
];
