/**
 * Live coding / implementation question specs for the question bank.
 * Each spec asks candidates to write real code from scratch.
 * Topics: JS utility functions, React custom hooks, and common algorithms.
 */
import type { QuestionSpec } from './question-spec-types';

export const CODING_CHALLENGE_SPECS: QuestionSpec[] = [
  // ── JavaScript utility implementations ──────────────────────────────────────

  {
    key: 'impl-debounce',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '⏳ Implement debounce',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a debounce function in JavaScript. It should delay invoking the callback until after a given wait time has elapsed since the last invocation. Support an optional leading option to call on the leading edge.',
    tags: ['debounce', 'closures', 'timers', 'implementation'],
  },
  {
    key: 'impl-throttle',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '⏱ Implement throttle',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a throttle function in JavaScript that ensures a callback is called at most once per given time window. Support both leading and trailing invocations and explain the difference between throttle and debounce.',
    tags: ['throttle', 'closures', 'timers', 'implementation'],
  },
  {
    key: 'impl-memoize',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '🧠 Implement memoize',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a generic memoize function that caches the results of a function call based on its arguments. Handle multiple arguments, support a custom cache key resolver, and discuss cache invalidation strategies.',
    tags: ['memoize', 'caching', 'closures', 'implementation'],
  },
  {
    key: 'impl-curry',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '🍛 Implement curry',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a curry function that transforms a function of N arguments into a chain of N single-argument functions. Your implementation should also support partial application — calling with fewer arguments than expected returns a new curried function.',
    tags: ['curry', 'closures', 'functional', 'implementation'],
  },
  {
    key: 'impl-deep-clone',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '🔂 Implement deep clone',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a deep clone function in JavaScript without using JSON.parse/JSON.stringify. Handle nested objects, arrays, Dates, RegExp, circular references, and explain why the JSON approach fails for these types.',
    tags: ['deep-clone', 'recursion', 'circular-reference', 'implementation'],
  },
  {
    key: 'impl-event-emitter',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '📡 Implement EventEmitter',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a JavaScript EventEmitter class with on, off, emit, and once methods. Support multiple listeners per event, prevent memory leaks with proper cleanup, and ensure once listeners remove themselves after a single call.',
    tags: ['event-emitter', 'pub-sub', 'classes', 'implementation'],
  },
  {
    key: 'impl-promise-all',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '🤝 Implement Promise.all',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement Promise.all from scratch. It should resolve when all promises resolve (preserving input order) and reject immediately when any promise rejects. Then implement Promise.allSettled and explain the difference.',
    tags: ['promises', 'async', 'concurrency', 'implementation'],
  },
  {
    key: 'impl-pipe-compose',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '🔗 Implement pipe and compose',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement pipe and compose functions for function composition. pipe executes left-to-right, compose right-to-left. Support any number of functions, handle async functions with pipeAsync, and demonstrate real use cases in a data transformation pipeline.',
    tags: ['pipe', 'compose', 'functional', 'higher-order', 'implementation'],
  },
  {
    key: 'impl-lru-cache',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '📦 Implement LRU cache',
    difficulty: 'senior',
    type: 'coding',
    question: 'Implement an LRU (Least Recently Used) cache class in JavaScript with get and put methods, both in O(1) time. Use a Map and doubly-linked list. Explain why a Map alone is insufficient for O(1) eviction.',
    tags: ['lru-cache', 'linked-list', 'map', 'algorithm', 'implementation'],
  },
  {
    key: 'impl-flatten-array',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '📐 Implement Array.flat',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement Array.prototype.flat from scratch — a function that flattens a nested array up to a given depth (default 1). Then implement flatMap. Provide both recursive and iterative solutions and compare their stack-overflow risk.',
    tags: ['array', 'recursion', 'iteration', 'implementation'],
  },

  // ── React custom hook implementations ────────────────────────────────────────

  {
    key: 'impl-use-debounce',
    file: 'react.json',
    topic: 'React',
    subtopic: '🪝 Implement useDebounce hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useDebounce custom React hook that delays updating a value until after a specified wait period. Handle cleanup to avoid state updates on unmounted components. Show how it improves a search-as-you-type input.',
    tags: ['react-hooks', 'debounce', 'cleanup', 'implementation'],
  },
  {
    key: 'impl-use-local-storage',
    file: 'react.json',
    topic: 'React',
    subtopic: '🗄 Implement useLocalStorage hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useLocalStorage custom React hook that syncs React state with localStorage. Handle SSR environments where localStorage is unavailable, JSON parse errors, and cross-tab synchronisation via the storage event.',
    tags: ['react-hooks', 'localStorage', 'ssr', 'implementation'],
  },
  {
    key: 'impl-use-previous',
    file: 'react.json',
    topic: 'React',
    subtopic: '⏮ Implement usePrevious hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a usePrevious hook that returns the previous value of any state or prop. Explain why useRef is used instead of useState for this pattern, and demonstrate how to use it to animate list items entering and leaving.',
    tags: ['react-hooks', 'useRef', 'patterns', 'implementation'],
  },
  {
    key: 'impl-use-intersection-observer',
    file: 'react.json',
    topic: 'React',
    subtopic: '👁 Implement useIntersectionObserver hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useIntersectionObserver custom React hook that tracks whether an element enters the viewport. Support threshold and rootMargin options, clean up the observer on unmount, and demonstrate lazy-loading images and infinite scroll with it.',
    tags: ['react-hooks', 'intersection-observer', 'lazy-loading', 'implementation'],
  },
  {
    key: 'impl-use-click-outside',
    file: 'react.json',
    topic: 'React',
    subtopic: '🖱 Implement useClickOutside hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useClickOutside custom React hook that calls a handler when a user clicks outside a given element. Handle both mousedown and touchstart events, support multiple refs, and explain event bubbling edge cases like portals.',
    tags: ['react-hooks', 'events', 'portals', 'implementation'],
  },
  {
    key: 'impl-use-media-query',
    file: 'react.json',
    topic: 'React',
    subtopic: '📱 Implement useMediaQuery hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useMediaQuery custom React hook that returns true/false based on a CSS media query string. Handle SSR safely, subscribe to matchMedia changes, and clean up on unmount. Show how to build a responsive component without Tailwind.',
    tags: ['react-hooks', 'media-query', 'ssr', 'responsive', 'implementation'],
  },
  {
    key: 'impl-use-fetch',
    file: 'react.json',
    topic: 'React',
    subtopic: '🌐 Implement useFetch hook',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a useFetch custom React hook that fetches data from a URL and returns { data, loading, error }. Handle race conditions with AbortController, prevent state updates on unmounted components, and support manual refetching.',
    tags: ['react-hooks', 'fetch', 'abort-controller', 'race-condition', 'implementation'],
  },
  {
    key: 'impl-use-reducer-thunk',
    file: 'react.json',
    topic: 'React',
    subtopic: '🎬 Implement useReducer with async actions',
    difficulty: 'senior',
    type: 'coding',
    question: 'Extend React\'s useReducer to support async thunk actions — similar to Redux Thunk. The enhanced dispatch should accept both plain action objects and async functions. Show how this simplifies complex async state flows compared to multiple useState calls.',
    tags: ['react-hooks', 'useReducer', 'async', 'state-management', 'implementation'],
  },

  // ── Algorithm implementations ─────────────────────────────────────────────

  {
    key: 'impl-deep-equal',
    file: 'javascript.json',
    topic: 'JavaScript',
    subtopic: '⚖️ Implement deep equality check',
    difficulty: 'mid',
    type: 'coding',
    question: 'Implement a deepEqual function that performs structural equality comparison for nested objects, arrays, Dates, null, and primitives. Discuss how it differs from === and JSON.stringify comparison, and handle circular references.',
    tags: ['deep-equal', 'recursion', 'circular-reference', 'implementation'],
  },
  {
    key: 'impl-virtual-dom-diff',
    file: 'react.json',
    topic: 'React',
    subtopic: '🌲 Implement a minimal virtual DOM diff',
    difficulty: 'senior',
    type: 'coding',
    question: 'Implement a minimal virtual DOM diffing algorithm (reconciler) that compares two vNode trees and produces a list of patches (CREATE, REMOVE, REPLACE, UPDATE attributes). Explain the O(n³) → O(n) heuristic React uses and why key props matter.',
    tags: ['virtual-dom', 'diffing', 'reconciliation', 'react', 'implementation'],
  },
];
