/**
 * Phase-4 content sprint: behavioral story specs.
 * Fills the gaps next to the existing 9 (debugging, product conflict,
 * leadership, impact, trade-off, learning, mentorship, scope pushback):
 * failure, incidents, feedback both ways, estimation, cross-team work,
 * influence, ambiguity, prioritization, and growth stories.
 */
import type { QuestionSpec } from './question-spec-types';

const FILE = 'behavioral.json';
const TOPIC = 'Behavioral';

export const BEHAVIORAL_STORY_SPECS: QuestionSpec[] = [
  {
    key: 'behavioral-failure-postmortem',
    file: FILE, topic: TOPIC,
    subtopic: '💥 Failure story',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a project that failed or was cancelled. What was your role, what would you do differently, and what did you change afterwards?',
    tags: ['failure', 'reflection', 'ownership', 'star-method'],
  },
  {
    key: 'behavioral-production-incident',
    file: FILE, topic: TOPIC,
    subtopic: '🚨 Production incident',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you caused or handled a production incident. How did you respond in the moment, communicate, and prevent it from recurring?',
    tags: ['incident', 'ownership', 'postmortem', 'communication'],
  },
  {
    key: 'behavioral-receiving-hard-feedback',
    file: FILE, topic: TOPIC,
    subtopic: '👂 Receiving feedback',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about the hardest piece of feedback you have received. How did you react, and what did you actually change?',
    tags: ['feedback', 'growth', 'self-awareness'],
  },
  {
    key: 'behavioral-giving-hard-feedback',
    file: FILE, topic: TOPIC,
    subtopic: '🗣 Giving feedback',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you had to give difficult feedback to a peer or someone senior to you. How did you approach it and what happened?',
    tags: ['feedback', 'communication', 'courage', 'peer-management'],
  },
  {
    key: 'behavioral-disagree-and-commit',
    file: FILE, topic: TOPIC,
    subtopic: '🤝 Disagree & commit',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a technical disagreement with another engineer where the team went against your recommendation. How did you handle it, and what was the outcome?',
    tags: ['disagreement', 'commitment', 'collaboration', 'ego'],
  },
  {
    key: 'behavioral-estimation-miss',
    file: FILE, topic: TOPIC,
    subtopic: '📅 Estimation miss',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time your estimate was significantly wrong and a deadline slipped. How did you communicate it, and how did you adjust?',
    tags: ['estimation', 'deadlines', 'communication', 'planning'],
  },
  {
    key: 'behavioral-cross-team-dependency',
    file: FILE, topic: TOPIC,
    subtopic: '🔗 Cross-team dependency',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time your project was blocked by another team. How did you unblock it without damaging the relationship?',
    tags: ['cross-team', 'dependencies', 'negotiation', 'collaboration'],
  },
  {
    key: 'behavioral-influence-without-authority',
    file: FILE, topic: TOPIC,
    subtopic: '🧲 Influence without authority',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you drove a significant change — technical or process — without having formal authority. How did you build buy-in?',
    tags: ['influence', 'leadership', 'buy-in', 'change-management'],
  },
  {
    key: 'behavioral-ambiguous-requirements',
    file: FILE, topic: TOPIC,
    subtopic: '🌫 Ambiguity',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about a time you were handed a vague or ambiguous problem. How did you turn it into something the team could execute on?',
    tags: ['ambiguity', 'requirements', 'clarification', 'initiative'],
  },
  {
    key: 'behavioral-competing-priorities',
    file: FILE, topic: TOPIC,
    subtopic: '⚖️ Competing priorities',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you had several urgent things competing for your time. How did you prioritize, and how did you communicate the trade-offs?',
    tags: ['prioritization', 'time-management', 'communication'],
  },
  {
    key: 'behavioral-legacy-codebase',
    file: FILE, topic: TOPIC,
    subtopic: '🏚 Legacy code',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about a time you inherited a messy or legacy codebase. How did you decide what to improve versus leave alone, and how did you deliver on top of it?',
    tags: ['legacy-code', 'refactoring', 'pragmatism', 'risk'],
  },
  {
    key: 'behavioral-tech-debt-advocacy',
    file: FILE, topic: TOPIC,
    subtopic: '🏗 Tech debt advocacy',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you convinced product or leadership to invest in paying down technical debt. How did you make the case in business terms?',
    tags: ['tech-debt', 'stakeholders', 'persuasion', 'business-impact'],
  },
  {
    key: 'behavioral-saying-no',
    file: FILE, topic: TOPIC,
    subtopic: '🙅 Saying no',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you said no to a stakeholder request. How did you deliver it, and what alternative did you offer?',
    tags: ['boundaries', 'stakeholders', 'negotiation', 'communication'],
  },
  {
    key: 'behavioral-difficult-teammate',
    file: FILE, topic: TOPIC,
    subtopic: '🧊 Difficult collaboration',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about a time you worked with someone you found difficult. What made it hard, and what did you do to make the collaboration work?',
    tags: ['conflict', 'empathy', 'collaboration', 'professionalism'],
  },
  {
    key: 'behavioral-decision-incomplete-data',
    file: FILE, topic: TOPIC,
    subtopic: '🎲 Deciding under uncertainty',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a high-stakes decision you made with incomplete information. How did you reason about the risk, and how did it play out?',
    tags: ['decision-making', 'uncertainty', 'risk', 'judgment'],
  },
  {
    key: 'behavioral-raising-quality-bar',
    file: FILE, topic: TOPIC,
    subtopic: '📈 Raising the quality bar',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you raised the engineering quality bar on your team — through code review culture, testing, or standards. What resistance did you hit?',
    tags: ['quality', 'code-review', 'culture', 'standards'],
  },
  {
    key: 'behavioral-changed-your-mind',
    file: FILE, topic: TOPIC,
    subtopic: '🔄 Changing your mind',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you held a strong technical opinion and then changed your mind. What evidence moved you, and what did you take away from it?',
    tags: ['humility', 'evidence', 'growth', 'judgment'],
  },
  {
    key: 'behavioral-technical-risk-bet',
    file: FILE, topic: TOPIC,
    subtopic: '🎯 Technical risk',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about the biggest technical risk you have taken — a new technology, an aggressive rewrite, an unproven approach. How did you de-risk it?',
    tags: ['risk', 'innovation', 'de-risking', 'judgment'],
  },
  {
    key: 'behavioral-knowledge-sharing',
    file: FILE, topic: TOPIC,
    subtopic: '📚 Knowledge sharing',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about something you did to make your team less dependent on you — documentation, onboarding, tooling, or teaching. What impact did it have?',
    tags: ['documentation', 'onboarding', 'bus-factor', 'teaching'],
  },
  {
    key: 'behavioral-speed-vs-quality-pressure',
    file: FILE, topic: TOPIC,
    subtopic: '⏩ Speed vs quality',
    difficulty: 'senior', type: 'behavioral',
    question: 'Tell me about a time you were pressured to ship faster than you were comfortable with. What corners did you refuse to cut, and which did you consciously accept?',
    tags: ['pressure', 'quality', 'trade-offs', 'integrity'],
  },
  {
    key: 'behavioral-skill-gap-growth',
    file: FILE, topic: TOPIC,
    subtopic: '🌱 Closing a skill gap',
    difficulty: 'mid', type: 'behavioral',
    question: 'Tell me about a skill gap you identified in yourself and deliberately closed. How did you structure the learning, and how did you apply it at work?',
    tags: ['growth', 'learning', 'self-awareness', 'initiative'],
  },
];
